image: google/cloud-sdk:alpine

stages:
  - fmt
  - validate
  - plan

variables:
  TF_ROOT: "environments/dev"

before_script:
  - echo $GOOGLE_CREDENTIALS | base64 -d > /tmp/google-credentials.json
  - export GOOGLE_APPLICATION_CREDENTIALS="/tmp/google-credentials.json"
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.11.3/terraform_1.11.3_linux_amd64.zip
  - unzip terraform.zip && mv terraform /usr/local/bin/
  - terraform -version

fmt:
  stage: fmt
  script:
    - cd $TF_ROOT
    - terraform fmt  # Automatically format the files
    - terraform fmt -check  # Ensure the files are correctly formatted

validate:
  stage: validate
  script:
    - cd $TF_ROOT
    - terraform init  # Don't use -backend=false unless necessary
    - terraform validate

plan:
  stage: plan
  script:
    - cd $TF_ROOT
    - terraform init
    - if [ -f "terraform.tfvars" ]; then terraform plan -var-file="terraform.tfvars"; else terraform plan; fi
